### ISSUE TITLE
Array to String conversion on line 240

### ISSUE THREAD

**Issue by faselunare** [wintercms/wn-builder-plugin#30]
```
PHP 8.0.16 (cli) (built: Mar  3 2022 06:25:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies
```
```
mysql  Ver 8.0.28 for macos12.2 on arm64 (Homebrew)
```
```
php artisan winter:version
*** Detecting Winter CMS build...
*** Detected a modified version of Winter CMS build 1.1.8.
```
```
Composer version 2.2.8
```
```
Composer show winter/storm

name     : winter/storm
descrip. : Winter CMS Storm Library
keywords : cms, storm, winter
versions : * dev-wip/1.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://wintercms.com
source   : [git] https://github.com/wintercms/storm.git c76f1facb74706d02f3499aceeaf8e7018115bfc
dist     : [zip] https://api.github.com/repos/wintercms/storm/zipball/c76f1facb74706d02f3499aceeaf8e7018115bfc c76f1facb74706d02f3499aceeaf8e7018115bfc
path     : /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm
names    : winter/storm, october/rain

support
source : https://github.com/wintercms/storm/tree/wip/1.2

autoload
files
psr-4
Winter\Storm\ => src/

requires
assetic/framework ~3.0
doctrine/dbal ^2.6
erusev/parsedown-extra ~0.7
ext-ctype *
ext-curl *
ext-dom *
ext-fileinfo *
ext-gd *
ext-json *
ext-libxml *
ext-mbstring *
ext-openssl *
ext-pdo *
ext-zip *
laravel/framework ~9.0
laravel/tinker ^2.7
league/csv ~9.1
nesbot/carbon ^2.0
php ^8.0.2
scssphp/scssphp ~1.0
symfony/yaml ^6.0
twig/twig ~3.0
wikimedia/less.php ~3.0
wikimedia/minify ~2.2

requires (dev)
dms/phpunit-arraysubset-asserts ^0.1.0|^0.2.1
meyfa/phpunit-assert-gd ^2.0.0|^3.0.0
mockery/mockery ^1.4.4
php-parallel-lint/php-parallel-lint ^1.0
phpunit/phpunit ^9.5.8
squizlabs/php_codesniffer 3.*

suggests
ext-PDO_ODBC Required to use databases accessed through ODBC drivers
ext-pdo_dblib Required to use MS SQL Server databases
ext-pdo_mysql Required to use MySQL databases
ext-pdo_pgsql Required to use PostgreSQL databases
ext-pdo_sqlite Required to use SQLite databases

replaces
october/rain self.version
```

Step to reporduce

#INSTALLATION
- composer create-project wintercms/winter example.com "dev-wip/1.2"
- php artisan winter:env (and db config)
- php artisan winter up
- composer require --dev winter/wn-builder-plugin

In the Builder plugin
- Create 2 tables
- In the Models page click ADD
and then get the error

<img width="520" alt="Screenshot 2022-03-15 at 23 11 36" src="https://user-images.githubusercontent.com/39338657/158482526-5a5f991c-afa7-4e76-bb86-ac8a1a3ad5e3.png">

**Comment by faselunare** [comment]
```
[2022-03-15 22:36:43] development.ERROR: ErrorException: Array to string conversion in /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/classes/ModelModel.php:240
Stack trace:
#0 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Array to string...', '/Users/francesc...', 240)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'Array to string...', '/Users/francesc...', 240)
#2 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/classes/ModelModel.php(240): array_combine(Array, Array)
#3 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/Form.php(1322): Winter\Builder\Classes\ModelModel->getDatabaseTableOptions(NULL, Object(Winter\Builder\Classes\ModelModel))
#4 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/Form.php(914): Backend\Widgets\Form->getOptionsFromModel(Object(Backend\Classes\FormField), NULL)
#5 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/FormField.php(232): Backend\Widgets\Form->Backend\Widgets\{closure}()
#6 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_field_dropdown.htm(2): Backend\Classes\FormField->options()
#7 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#8 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#9 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/Form.php(275): Backend\Classes\WidgetBase->makePartial('_field_dropdown...', Array)
#10 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_field.htm(22): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField))
#11 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#12 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#13 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_field-container.htm(8): Backend\Classes\WidgetBase->makePartial('_field.htm', Array)
#14 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#15 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#16 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_form_fields.htm(2): Backend\Classes\WidgetBase->makePartial('_field-containe...', Array)
#17 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#18 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#19 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_section.htm(17): Backend\Classes\WidgetBase->makePartial('_form_fields.ht...', Array)
#20 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#21 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#22 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_form.htm(3): Backend\Classes\WidgetBase->makePartial('_section.htm', Array)
#23 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#24 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#25 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/form/partials/_form-container.htm(8): Backend\Classes\WidgetBase->makePartial('_form.htm')
#26 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#27 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\WidgetBase->makeFileContents('/Users/francesc...', Array)
#28 /Users/francesco/Dev/sites/wn-conference/modules/backend/Widgets/Form.php(228): Backend\Classes\WidgetBase->makePartial('_form-container...', Array)
#29 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/behaviors/indexmodeloperations/partials/_model-popup-form.htm(10): Backend\Widgets\Form->render()
#30 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(246): include('/Users/francesc...')
#31 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/ControllerBehavior.php(153): Backend\Classes\Controller->makeFileContents('/Users/francesc...', Array)
#32 /Users/francesco/Dev/sites/wn-conference/modules/system/Traits/ViewMaker.php(96): Backend\Classes\ControllerBehavior->makeFileContents('/Users/francesc...', Array)
#33 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/behaviors/IndexModelOperations.php(34): Backend\Classes\ControllerBehavior->makePartial('_model-popup-fo...')
#34 [internal function]: Winter\Builder\Behaviors\IndexModelOperations->onModelLoadPopup()
#35 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Extension/ExtendableTrait.php(432): call_user_func_array(Array, Array)
#36 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(184): Backend\Classes\Controller->extendableCall('onModelLoadPopu...', Array)
#37 [internal function]: Backend\Classes\Controller->__call('onModelLoadPopu...', Array)
#38 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(629): call_user_func_array(Array, Array)
#39 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(479): Backend\Classes\Controller->runAjaxHandler('onModelLoadPopu...')
#40 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(277): Backend\Classes\Controller->execAjaxHandlers()
#41 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(171): Backend\Classes\Controller->run('index', Array)
#42 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run('winter/builder')
#43 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(119): Illuminate\Routing\Controller->callAction('run', Array)
#44 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Backend\Classes\BackendController->callAction('run', Array)
#45 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#46 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#47 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#48 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#57 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#66 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#67 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Winter\Storm\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#68 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#69 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForTrustedProxies.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForTrustedProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Http/Middleware/TrustHosts.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Http\Middleware\TrustHosts->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#78 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#79 /Users/francesco/Dev/sites/wn-conference/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#80 /Users/francesco/.composer/vendor/laravel/valet/server.php(234): require('/Users/francesc...')
#81 {main}  

```

**Comment by bennothommo** [comment]
Thanks @faselunare - I've applied a hotfix here: https://github.com/wintercms/wn-builder-plugin/commit/651f6542a1420161b5ea2ccccd3284e541180ef9. Will make a hot-fix release now.

**Comment by faselunare** [comment]
Thanks!
