### ISSUE TITLE
Error creating dropdown in fields.yaml

### ISSUE THREAD

**Issue by faselunare** [wintercms/wn-builder-plugin#33]
When creating fields.yaml 
if the field il of type DROPDOWN
when saving, I get this error

<img width="995" alt="Screenshot 2022-03-20 at 16 11 19" src="https://user-images.githubusercontent.com/39338657/159169141-7c198df6-36fa-4074-9335-cd4441e813af.png">

stack trace
``` 
[2022-03-20 15:11:57] development.ERROR: ErrorException: Undefined array key "multiple" in /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/classes/ModelFormModel.php:103
Stack trace:
#0 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Undefined array...', '/Users/francesc...', 103)
#1 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/classes/ModelFormModel.php(103): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'Undefined array...', '/Users/francesc...', 103)
#2 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/classes/ModelFormModel.php(57): Winter\Builder\Classes\ModelFormModel->scanJsonableFields(Array, Array)
#3 /Users/francesco/Dev/sites/wn-conference/plugins/winter/builder/behaviors/IndexModelFormOperations.php(71): Winter\Builder\Classes\ModelFormModel->getJsonableFields()
#4 [internal function]: Winter\Builder\Behaviors\IndexModelFormOperations->onModelFormSave()
#5 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Extension/ExtendableTrait.php(432): call_user_func_array(Array, Array)
#6 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(184): Backend\Classes\Controller->extendableCall('onModelFormSave', Array)
#7 [internal function]: Backend\Classes\Controller->__call('onModelFormSave', Array)
#8 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(629): call_user_func_array(Array, Array)
#9 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(479): Backend\Classes\Controller->runAjaxHandler('onModelFormSave')
#10 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/Controller.php(277): Backend\Classes\Controller->execAjaxHandlers()
#11 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(171): Backend\Classes\Controller->run('index', Array)
#12 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run('winter/builder')
#13 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(119): Illuminate\Routing\Controller->callAction('run', Array)
#14 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Backend\Classes\BackendController->callAction('run', Array)
#15 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#16 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#17 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#18 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /Users/francesco/Dev/sites/wn-conference/modules/backend/Classes/BackendController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#27 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#36 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Winter\Storm\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#38 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Foundation/Http/Middleware/CheckForTrustedProxies.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Foundation\Http\Middleware\CheckForTrustedProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Http/Middleware/TrustHosts.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Winter\Storm\Http\Middleware\TrustHosts->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /Users/francesco/Dev/sites/wn-conference/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /Users/francesco/Dev/sites/wn-conference/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 /Users/francesco/.composer/vendor/laravel/valet/server.php(234): require('/Users/francesc...')
#51 {main}  

```

**Comment by Geraldhub** [comment]
Any solution?

**Comment by LukeTowers** [comment]
Fixed in https://github.com/wintercms/wn-builder-plugin/commit/36075870087aef719ccfa394c1d603ed8a9b2665, thanks for checking in @Geraldhub and for the original report @faselunare!
